#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i 's/listen [0-9]\+;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "hello world" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx status
