#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=0
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]; then
        echo "Hi"
        x=$(( x + 1 ))
    fi
    
    echo "Best School"
    ((x++))
done
